---
- name: Deploy prereqs for dev boxes
  hosts: docker_hosts
  become_method: sudo
  tasks:
    - name: Install packages
      become: yes
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-apt
        state: present

    - name: Add Docker’s official GPG key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    
    - name: Get ubuntu release
      command: lsb_release -cs
      register: release_register
      changed_when: false

    - name: Set up the stable docker repository
      become: yes
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu {{ release_register.stdout | trim }} stable
        state: present

    - name: Install packages
      become: yes
      ansible.builtin.package:
        name:
          - docker-ce 
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Register username on host
      command: whoami
      register: username_register
      changed_when: false

    - name: Add current user to docker group
      become: yes
      command: "adduser {{ username_register.stdout | trim }} docker"

    - name: Register OS name
      command: uname -s
      register: os_name_register
      changed_when: false

    - name: Register OS architecture
      command: uname -m
      register: os_arch_register
      changed_when: false

    - name: Download docker-compose
      become: yes
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        checksum: sha256:8097769d32e34314125847333593c8edb0dfc4a5b350e4839bef8c2fe8d09de7

    - name: Apply executable permissions to the docker-compose binary
      become: yes
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: a+x
