version: "3.9"
services:
  image_subscriber:
    build: 
      context: .
      dockerfile: Dockerfile.subscriber
    ports:
      - "8080:8080"
  image_publisher:
    build: 
      context: .
      dockerfile: Dockerfile.publisher
